#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[CH3] + [CH3] <=> ethane",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(9.45e+14,'cm^3/(mol*s)'), n=-0.538, Ea=(135.1,'cal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(2000,'K'), comment="""Matched reaction 9 CH3 + CH3 <=> C2H6 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 9 CH3 + CH3 <=> C2H6 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing]
family: R_Recombination
""",
)

entry(
    index = 1,
    label = "[CH3] + ethane <=> C + C[CH2]",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(35,'cm^3/(mol*s)'), n=3.44, Ea=(10384,'cal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K'), comment="""Matched reaction 215 C2H6 + CH3_r3 <=> C2H5b + CH4 in H_Abstraction/training
    This reaction matched rate rule [C/H3/Cs\H3;C_methyl]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 215 C2H6 + CH3_r3 <=> C2H5b + CH4 in H_Abstraction/training
This reaction matched rate rule [C/H3/Cs\H3;C_methyl]
family: H_Abstraction
""",
)

entry(
    index = 2,
    label = "[H] + C[CH2] <=> ethane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)','+|-',1e+13), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), comment="""Matched reaction 58 H + C2H5 <=> C2H6-2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 58 H + C2H5 <=> C2H6-2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN]
family: R_Recombination
""",
)

entry(
    index = 3,
    label = "[H] + [CH3] <=> C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.93e+14,'cm^3/(mol*s)'), n=0, Ea=(1.12968,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 57 H + CH3 <=> CH4 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_N-2CNO->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 57 H + CH3 <=> CH4 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_N-2CNO->O]
family: R_Recombination
""",
)

entry(
    index = 4,
    label = "[H] + C=C <=> C[CH2]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.62e+08,'cm^3/(mol*s)'), n=1.64, Ea=(4.22584,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2541 H + C2H4 <=> C2H5-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2541 H + C2H4 <=> C2H5-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 5,
    label = "[CH3] + C[CH2] <=> C + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(6.57e+14,'cm^3/(mol*s)','*|/',1.1), n=-0.68, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 5 CH3_r1 + C2H5 <=> CH4 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C_2R!H->C]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 5 CH3_r1 + C2H5 <=> CH4 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C_2R!H->C]
family: Disproportionation
""",
)

entry(
    index = 6,
    label = "C[CH2] + C[CH2] <=> C=C + ethane",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(6.9e+13,'cm^3/(mol*s)','*|/',1.1), n=-0.35, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 6 C2H5 + C2H5-2 <=> C2H6 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 6 C2H5 + C2H5-2 <=> C2H6 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C]
family: Disproportionation
""",
)

entry(
    index = 7,
    label = "[H] + ethane <=> [H][H] + C[CH2]",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(1.15e+08,'cm^3/(mol*s)'), n=1.9, Ea=(7530,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 210 C2H6 + H <=> C2H5b + H2_p in H_Abstraction/training
    This reaction matched rate rule [C/H3/Cs\H3;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 210 C2H6 + H <=> C2H5b + H2_p in H_Abstraction/training
This reaction matched rate rule [C/H3/Cs\H3;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 8,
    label = "[H] + C[CH2] <=> [H][H] + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1.083e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_2R!H->C]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_2R!H->C]
family: Disproportionation
""",
)

entry(
    index = 9,
    label = "[H] + C <=> [H][H] + [CH3]",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(4100,'cm^3/(mol*s)'), n=3.156, Ea=(8755,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 186 CH4b + H <=> CH3_p1 + H2_p in H_Abstraction/training
    This reaction matched rate rule [C_methane;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 186 CH4b + H <=> CH3_p1 + H2_p in H_Abstraction/training
This reaction matched rate rule [C_methane;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 10,
    label = "[H] + [H] <=> [H][H]",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 11,
    label = "[H] + [CH]=C <=> C=C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.21e+14,'cm^3/(mol*s)','+|-',4.82e+13), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), comment="""Matched reaction 60 H + C2H3 <=> C2H4 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 60 H + C2H3 <=> C2H4 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 12,
    label = "C + [CH]=C <=> [CH3] + C=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(0.02236,'cm^3/(mol*s)'), n=4.34, Ea=(23.8488,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 842 C2H3 + CH4b <=> C2H4 + CH3_p23 in H_Abstraction/training
    This reaction matched rate rule [Cd/H2/NonDeC;C_methyl]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 842 C2H3 + CH4b <=> C2H4 + CH3_p23 in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;C_methyl]
family: H_Abstraction
""",
)

entry(
    index = 13,
    label = "[CH]=C + ethane <=> C=C + C[CH2]",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(0.00108,'cm^3/(mol*s)'), n=4.55, Ea=(14.644,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 774 C2H3 + C2H6 <=> C2H4 + C2H5 in H_Abstraction/training
    This reaction matched rate rule [Cd/H2/NonDeC;C_rad/H2/Cs\H3]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 774 C2H3 + C2H6 <=> C2H4 + C2H5 in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;C_rad/H2/Cs\H3]
family: H_Abstraction
""",
)

entry(
    index = 14,
    label = "[H] + C=C <=> [H][H] + [CH]=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(240,'cm^3/(mol*s)'), n=3.62, Ea=(11266,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 217 C2H4 + H <=> C2H3_p + H2_p in H_Abstraction/training
    This reaction matched rate rule [Cd/H2/NonDeC;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 217 C2H4 + H <=> C2H3_p + H2_p in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 15,
    label = "[CH]=C + C[CH2] <=> C=C + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(4.56e+14,'cm^3/(mol*s)','*|/',1.5), n=-0.7, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 11 C2H3-2 + C2H5 <=> C2H4-2 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 11 C2H3-2 + C2H5 <=> C2H4-2 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS]
family: Disproportionation
""",
)

entry(
    index = 16,
    label = "[H] + C#C <=> [CH]=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.03e+09,'cm^3/(mol*s)'), n=1.64, Ea=(8.82824,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2697 H + C2H2 <=> C2H3-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Ct-H_Ct-H;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2697 H + C2H2 <=> C2H3-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Ct-H_Ct-H;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 17,
    label = "[CH]=C + C[CH2] <=> C#C + ethane",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.10638e+07,'m^3/(mol*s)'), n=-0.250519, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.1636050951277374, var=0.25119831907169365, Tref=1000.0, N=5, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 18,
    label = "[CH3] + [CH]=C <=> C + C#C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.62,'m^3/(mol*s)'), n=1.87, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_N-Sp-2R!H-1C',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_N-Sp-2R!H-1C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_N-Sp-2R!H-1C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 19,
    label = "[CH]=C + [CH]=C <=> C#C + C=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.9597e+07,'m^3/(mol*s)'), n=-0.311932, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.14761419944759951, var=0.2702865095049491, Tref=1000.0, N=6, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 20,
    label = "[H] + [CH]=C <=> [H][H] + C#C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(480,'m^3/(mol*s)'), n=1.5, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C',), comment="""Estimated from node Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 21,
    label = "[C]=C-2 <=> C#C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.59971e+13,'s^-1'), n=-0.201832, Ea=(34.0789,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [singletcarbene_CH;singletcarbene;CH] for rate rule [CdJ2=C;CdJ2;CdH2]
    Euclidian distance = 1.7320508075688772
    Multiplied by reaction path degeneracy 2.0
    family: Singlet_Carbene_Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using template [singletcarbene_CH;singletcarbene;CH] for rate rule [CdJ2=C;CdJ2;CdH2]
Euclidian distance = 1.7320508075688772
Multiplied by reaction path degeneracy 2.0
family: Singlet_Carbene_Intra_Disproportionation
""",
)

entry(
    index = 22,
    label = "[CH3] + C=C <=> [CH2]CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(861,'cm^3/(mol*s)'), n=2.988, Ea=(7.238,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2902 CH3 + C2H4 <=> C3H7 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-HHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2902 CH3 + C2H4 <=> C3H7 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-HHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 23,
    label = "[CH]=C + C=C <=> [CH2]CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(28600,'cm^3/(mol*s)'), n=2.41, Ea=(7.5312,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 234 C2H3 + C2H4 <=> C4H7-3 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CdsJ-H]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 234 C2H3 + C2H4 <=> C4H7-3 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CdsJ-H]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 24,
    label = "[CH2]CC=C <=> [CH2]C1CC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.32e+08,'s^-1'), n=0.97, Ea=(8.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 335 C4H7 <=> C4H7-2 in Intra_R_Add_Exocyclic/training
    This reaction matched rate rule [R4_S_D;doublebond_intra_2H_pri;radadd_intra_cs2H]
    family: Intra_R_Add_Exocyclic"""),
    longDesc = 
"""
Matched reaction 335 C4H7 <=> C4H7-2 in Intra_R_Add_Exocyclic/training
This reaction matched rate rule [R4_S_D;doublebond_intra_2H_pri;radadd_intra_cs2H]
family: Intra_R_Add_Exocyclic
""",
)

entry(
    index = 25,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 26,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.72e+06,'s^-1'), n=1.99, Ea=(27.2,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/Cd]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/Cd]
family: intra_H_migration
""",
)

entry(
    index = 27,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 28,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.72e+06,'s^-1'), n=1.99, Ea=(27.2,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_H/Cd;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_H/Cd;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 29,
    label = "[H] + C=CC=C <=> [CH2]CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.24e+08,'cm^3/(mol*s)'), n=1.64, Ea=(10.0416,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2580 H + C4H6-2 <=> C4H7-11 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-CdH_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2580 H + C4H6-2 <=> C4H7-11 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-CdH_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 30,
    label = "[H] + C=CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.62e+08,'cm^3/(mol*s)'), n=1.64, Ea=(-1.96648,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2544 H + C4H6 <=> C4H7-9 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-CdH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2544 H + C4H6 <=> C4H7-9 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-CdH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 31,
    label = "[CH]=C + [CH]=C <=> C=CC=C",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(3.615e+13,'cm^3/(mol*s)','+|-',1.2e+13), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), comment="""Matched reaction 89 C2H3 + C2H3 <=> C4H6-4 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_N-Sp-3R!H-2R_N-3R!H->O_N-Sp-3CCSS#2R_Ext-1C-R]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 89 C2H3 + C2H3 <=> C4H6-4 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_N-Sp-3R!H-2R_N-3R!H->O_N-Sp-3CCSS#2R_Ext-1C-R]
family: R_Recombination
""",
)

entry(
    index = 32,
    label = "C[CH2] + [CH2]CC=C <=> ethane + C=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.9417e+06,'m^3/(mol*s)'), n=-0.0393785, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.0327092327690802, var=0.00213978781668374, Tref=1000.0, N=2, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 33,
    label = "C[CH2] + [CH2]C=CC <=> ethane + C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(150000,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-2R!H-R_2R!H->C_4R->C',), comment="""Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 34,
    label = "[CH3] + [CH2]CC=C <=> C + C=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.3e+07,'m^3/(mol*s)'), n=-0.32, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_4C-u1',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_4C-u1
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_4C-u1
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 35,
    label = "[CH3] + [CH2]C=CC <=> C + C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(150000,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-2R!H-R_2R!H->C_4R->C',), comment="""Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 36,
    label = "[CH]=C + [CH2]CC=C <=> C=C + C=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.42e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 37,
    label = "[CH]=C + [CH2]C=CC <=> C=C + C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(150000,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-2R!H-R_2R!H->C_4R->C',), comment="""Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 38,
    label = "[H] + [CH2]CC=C <=> [H][H] + C=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.62e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_N-4CHNS->C',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_N-4CHNS->C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_N-4CHNS->C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 39,
    label = "[H] + [CH2]C=CC <=> [H][H] + C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(2.169e+07,'m^3/(mol*s)'), n=0, Ea=(16.6777,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-2R!H-R_2R!H->C_N-4R->C',), comment="""Estimated from node Root_Ext-2R!H-R_2R!H->C_N-4R->C
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-2R!H-R_2R!H->C_N-4R->C
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 40,
    label = "C=CC=C <=> C1=CCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.99998e+11,'s^-1'), n=0.0559095, Ea=(122.413,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH2_1;CdH2_2]
    Euclidian distance = 1.4142135623730951
    family: Intra_2+2_cycloaddition_Cd"""),
    longDesc = 
"""
Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH2_1;CdH2_2]
Euclidian distance = 1.4142135623730951
family: Intra_2+2_cycloaddition_Cd
""",
)

entry(
    index = 41,
    label = "[H] + C=C=CC <=> [CH2]C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.46e+08,'cm^3/(mol*s)'), n=1.64, Ea=(15.8155,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2714 H + C4H6-4 <=> C4H7-13 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Ca_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2714 H + C4H6-4 <=> C4H7-13 in R_Addition_MultipleBond/training
This reaction matched rate rule [Ca_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 42,
    label = "C=C=CC <=> C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1.05228e-61,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 43,
    label = "C[CH2] + [CH2]C=CC <=> ethane + C=C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(964000,'m^3/(mol*s)'), n=0, Ea=(26.7138,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Sp-6R!H-4CHNS',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Sp-6R!H-4CHNS"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Sp-6R!H-4CHNS
""",
)

entry(
    index = 44,
    label = "[CH3] + [CH2]C=CC <=> C + C=C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.433929,'m^3/(mol*s)'), n=1.96758, Ea=(8.5546,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.1692521391030103, var=6.079427974794933, Tref=1000.0, N=6, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H
""",
)

entry(
    index = 45,
    label = "[CH]=C + [CH2]C=CC <=> C=C + C=C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_N-Sp-6R!H-4CHNS',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_N-Sp-6R!H-4CHNS"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_N-Sp-6R!H-4CHNS
""",
)

entry(
    index = 46,
    label = "[H] + [CH2]C=CC <=> [H][H] + C=C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13564.2,'m^3/(mol*s)'), n=0.470009, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-2.1185860084328203, var=34.56885654617875, Tref=1000.0, N=33, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O
""",
)

entry(
    index = 47,
    label = "[H] + [CH2]C=C[CH2] <=> [CH2]CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.53274e+07,'m^3/(mol*s)'), n=0.153073, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.00248871722291, var=1.13870876508, Tref=1000.0, N=5, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_Ext-2CN-R',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_Ext-2CN-R
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_Ext-2CN-R
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 48,
    label = "C[CH2] + [CH2]C=C[CH2] <=> C=C + [CH2]CC=C",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(4.66096e+09,'m^3/(mol*s)'), n=-0.9, Ea=(6.04625,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.0763652085225523e-17, var=0.04891149884417046, Tref=1000.0, N=2, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R
    Multiplied by reaction path degeneracy 6.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R
Multiplied by reaction path degeneracy 6.0
""",
)

entry(
    index = 49,
    label = "[CH]=C + [CH2]C=C[CH2] <=> C#C + [CH2]CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(4.21276e+07,'m^3/(mol*s)'), n=-0.250519, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.1636050951277374, var=0.25119831907169365, Tref=1000.0, N=5, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
    Multiplied by reaction path degeneracy 4.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
Multiplied by reaction path degeneracy 4.0
""",
)

entry(
    index = 50,
    label = "[H] + [CH2]C=C[CH2] <=> [CH2]C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.25196e+07,'m^3/(mol*s)'), n=0.255122, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 51,
    label = "C[CH2] + [CH2]C=C[CH2] <=> C=C + [CH2]C=CC",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(1.374e+08,'m^3/(mol*s)'), n=-0.35, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R
    Multiplied by reaction path degeneracy 6.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R
Multiplied by reaction path degeneracy 6.0
""",
)

entry(
    index = 52,
    label = "[CH]=C + [CH2]C=C[CH2] <=> C#C + [CH2]C=CC",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(4.21276e+07,'m^3/(mol*s)'), n=-0.250519, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.1636050951277374, var=0.25119831907169365, Tref=1000.0, N=5, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
    Multiplied by reaction path degeneracy 4.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
Multiplied by reaction path degeneracy 4.0
""",
)

entry(
    index = 53,
    label = "[CH2]C=C[CH2] + [CH2]CC=C <=> C=CC=C + [CH2]C=CC",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(5.8e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C_Ext-6C-R',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C_Ext-6C-R
    Multiplied by reaction path degeneracy 4.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C_Ext-6C-R
Multiplied by reaction path degeneracy 4.0
""",
)

entry(
    index = 54,
    label = "[CH2]C=C[CH2] + [CH2]C=CC <=> C=CC=C + [CH2]C=CC",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(300000,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-2R!H-R_2R!H->C_4R->C',), comment="""Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
    Multiplied by reaction path degeneracy 6.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
Multiplied by reaction path degeneracy 6.0
""",
)

entry(
    index = 55,
    label = "[CH2]C=C[CH2] <=> C1=CCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.62e+12,'s^-1'), n=-0.305, Ea=(8.28432,'kJ/mol'), T0=(1,'K'), Tmin=(600,'K'), Tmax=(2000,'K'), comment="""Estimated using template [R4;C_rad_out_2H;Cpri_rad_out_2H] for rate rule [R4_SDS;C_rad_out_2H;Cpri_rad_out_2H]
    Euclidian distance = 1.0
    family: Birad_recombination"""),
    longDesc = 
"""
Estimated using template [R4;C_rad_out_2H;Cpri_rad_out_2H] for rate rule [R4_SDS;C_rad_out_2H;Cpri_rad_out_2H]
Euclidian distance = 1.0
family: Birad_recombination
""",
)

entry(
    index = 56,
    label = "[CH2]C=C[CH2] <=> C=C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.4874e+09,'s^-1'), n=1.045, Ea=(63.4002,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R3radExo;Y_rad;XH_Rrad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [R3radExo;Y_rad;XH_Rrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 57,
    label = "[CH2]C=C[CH2] => C=CC=C",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(5.01e+07,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 5 C4H6 => C4H6-2 in 1,2-Birad_to_alkene/training
    This reaction matched rate rule [Y_12_01]
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Matched reaction 5 C4H6 => C4H6-2 in 1,2-Birad_to_alkene/training
This reaction matched rate rule [Y_12_01]
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 58,
    label = "C#C + C[CH2] <=> [CH]=CCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(13600,'cm^3/(mol*s)'), n=2.41, Ea=(25.9408,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2254 C2H2 + C2H5 <=> C4H7-6 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Ct-H_Ct-H;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2254 C2H2 + C2H5 <=> C4H7-6 in R_Addition_MultipleBond/training
This reaction matched rate rule [Ct-H_Ct-H;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 59,
    label = "[CH]=CCC <=> [CH2]CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(111300,'s^-1'), n=2.23, Ea=(44.3086,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R4H_DSS;Cd_rad_out_singleH;Cs_H_out] for rate rule [R4H_DSS;Cd_rad_out_singleH;Cs_H_out_2H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R4H_DSS;Cd_rad_out_singleH;Cs_H_out] for rate rule [R4H_DSS;Cd_rad_out_singleH;Cs_H_out_2H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: intra_H_migration
""",
)

entry(
    index = 60,
    label = "[CH]=CCC <=> [CH2]C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.846e+10,'s^-1'), n=0.74, Ea=(145.185,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 194 C4H7-4 <=> C4H7-5 in intra_H_migration/training
    This reaction matched rate rule [R3H_SD;C_rad_out_H/NonDeC;Cd_H_out_singleH]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 194 C4H7-4 <=> C4H7-5 in intra_H_migration/training
This reaction matched rate rule [R3H_SD;C_rad_out_H/NonDeC;Cd_H_out_singleH]
family: intra_H_migration
""",
)

entry(
    index = 61,
    label = "C#C + [CH]=C <=> [CH]=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.168e+07,'cm^3/(mol*s)'), n=1.997, Ea=(5.452,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 196 C2H2 + C2H3 <=> C4H5-8 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Ct-H_Ct-H;CdsJ-H]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 196 C2H2 + C2H3 <=> C4H5-8 in R_Addition_MultipleBond/training
This reaction matched rate rule [Ct-H_Ct-H;CdsJ-H]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 62,
    label = "[H] + [CH]=CC=C <=> C=CC=C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.15666e+12,'m^3/(mol*s)'), n=-1.49308, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.399348053434, var=9.35827249741, Tref=1000.0, N=6, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O
""",
)

entry(
    index = 63,
    label = "[CH3] + C=CC=C <=> C + [CH]=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(0.03432,'cm^3/(mol*s)'), n=4.34, Ea=(86.6506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""From training reaction 1566 used for Cd/H2/NonDeC;C_methyl
    Exact match found for rate rule [Cd/H2/NonDeC;C_methyl]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 1566 used for Cd/H2/NonDeC;C_methyl
Exact match found for rate rule [Cd/H2/NonDeC;C_methyl]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 64,
    label = "C[CH2] + C=CC=C <=> ethane + [CH]=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(632,'cm^3/(mol*s)','*|/',10), n=3.13, Ea=(75.312,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""From training reaction 343 used for Cd/H2/NonDeC;C_rad/H2/Cs\H3
    Exact match found for rate rule [Cd/H2/NonDeC;C_rad/H2/Cs\H3]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 343 used for Cd/H2/NonDeC;C_rad/H2/Cs\H3
Exact match found for rate rule [Cd/H2/NonDeC;C_rad/H2/Cs\H3]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 65,
    label = "[H] + C=CC=C <=> [H][H] + [CH]=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(240,'cm^3/(mol*s)'), n=3.62, Ea=(47.1369,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 217 used for Cd/H2/NonDeC;H_rad
    Exact match found for rate rule [Cd/H2/NonDeC;H_rad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 217 used for Cd/H2/NonDeC;H_rad
Exact match found for rate rule [Cd/H2/NonDeC;H_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 66,
    label = "C[CH2] + [CH]=CC=C <=> C=C + C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(4.56e+08,'m^3/(mol*s)'), n=-0.7, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 67,
    label = "[CH]=C + C=CC=C <=> C=C + [CH]=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(0.0003437,'cm^3/(mol*s)'), n=4.732, Ea=(6.579,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 177 C4H6-3 + C2H3 <=> C2H4 + C4H5 in H_Abstraction/training
    This reaction matched rate rule [Cd/H2/NonDeC;Cd_Cd\H2_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 177 C4H6-3 + C2H3 <=> C2H4 + C4H5 in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;Cd_Cd\H2_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 68,
    label = "[CH]=C + [CH]=CC=C <=> C#C + C=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.9597e+07,'m^3/(mol*s)'), n=-0.311932, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.14761419944759951, var=0.2702865095049491, Tref=1000.0, N=6, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 69,
    label = "[CH]=CC=C + [CH2]CC=C <=> C=CC=C + C=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.42e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 70,
    label = "[CH]=CC=C + [CH2]C=CC <=> C=CC=C + C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(150000,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-2R!H-R_2R!H->C_4R->C',), comment="""Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_Ext-2R!H-R_2R!H->C_4R->C
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 71,
    label = "[CH]=CC=C + [CH2]C=CC <=> C=C=CC + C=CC=C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(84300,'m^3/(mol*s)'), n=0, Ea=(8.26808,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-6R!H-R',), comment="""Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-6R!H-R"""),
    longDesc = 
"""
Estimated from node Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-6R!H-R
""",
)

entry(
    index = 72,
    label = "[CH]=CC=C <=> [CH2]C1C=C1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.54e+10,'s^-1'), n=0.69, Ea=(105.312,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 14 used for R4_D_D;doublebond_intra_2H_pri;radadd_intra_cdsingleH
    Exact match found for rate rule [R4_D_D;doublebond_intra_2H_pri;radadd_intra_cdsingleH]
    Euclidian distance = 0
    family: Intra_R_Add_Exocyclic"""),
    longDesc = 
"""
From training reaction 14 used for R4_D_D;doublebond_intra_2H_pri;radadd_intra_cdsingleH
Exact match found for rate rule [R4_D_D;doublebond_intra_2H_pri;radadd_intra_cdsingleH]
Euclidian distance = 0
family: Intra_R_Add_Exocyclic
""",
)

entry(
    index = 73,
    label = "[CH3] + C#C <=> [CH]=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(133800,'cm^3/(mol*s)'), n=2.41, Ea=(28.3257,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2253 C2H2 + CH3 <=> C3H5-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Ct-H_Ct-H;CsJ-HHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2253 C2H2 + CH3 <=> C3H5-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Ct-H_Ct-H;CsJ-HHH]
family: R_Addition_MultipleBond
""",
)

