#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[CH2]CCCCC + [CH2]CCCCC <=> n-dodecane",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(1.703e+12,'cm^3/(mol*s)'), n=0.211, Ea=(0.007,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 156 C6H13 + C6H13 <=> C12H26-6 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 156 C6H13 + C6H13 <=> C12H26-6 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
family: R_Recombination
""",
)

entry(
    index = 1,
    label = "C[CH2] + [CH2]CCCCCCCCC <=> n-dodecane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.918e+12,'cm^3/(mol*s)'), n=0.213, Ea=(-0.001,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 152 C10H21 + C2H5 <=> C12H26-2 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 152 C10H21 + C2H5 <=> C12H26-2 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
family: R_Recombination
""",
)

entry(
    index = 2,
    label = "[CH2]CC + [CH2]CCCCCCCC <=> n-dodecane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.942e+12,'cm^3/(mol*s)'), n=0.212, Ea=(0.004,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 153 C9H19 + C3H7 <=> C12H26-3 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 153 C9H19 + C3H7 <=> C12H26-3 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
family: R_Recombination
""",
)

entry(
    index = 3,
    label = "[CH2]CCC + [CH2]CCCCCCC <=> n-dodecane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.674e+12,'cm^3/(mol*s)'), n=0.22, Ea=(-0.014,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 154 C8H17 + C4H9-2 <=> C12H26-4 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 154 C8H17 + C4H9-2 <=> C12H26-4 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
family: R_Recombination
""",
)

entry(
    index = 4,
    label = "[CH2]CCCC + [CH2]CCCCCC <=> n-dodecane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.737e+12,'cm^3/(mol*s)'), n=0.21, Ea=(0.006,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 155 C7H15 + C5H11 <=> C12H26-5 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 155 C7H15 + C5H11 <=> C12H26-5 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R]
family: R_Recombination
""",
)

entry(
    index = 5,
    label = "C=C + [CH2]CCC <=> [CH2]CCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(27.08,'cm^3/(mol*s)'), n=2.995, Ea=(6.503,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2905 C4H9-1 + C2H4 <=> C6H13-10 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2905 C4H9-1 + C2H4 <=> C6H13-10 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 6,
    label = "C=C + [CH2]CCCCCCC <=> [CH2]CCCCCCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(18.44,'cm^3/(mol*s)'), n=3.009, Ea=(6.446,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2909 C8H17-8 + C2H4 <=> C10H21-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2909 C8H17-8 + C2H4 <=> C10H21-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 7,
    label = "C=C + [CH2]CCCCCC <=> [CH2]CCCCCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(21.89,'cm^3/(mol*s)'), n=3.015, Ea=(6.396,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2908 C7H15-10 + C2H4 <=> C9H19-4 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2908 C7H15-10 + C2H4 <=> C9H19-4 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 8,
    label = "[CH3] + C=C <=> [CH2]CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(861,'cm^3/(mol*s)'), n=2.988, Ea=(7.238,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2902 CH3 + C2H4 <=> C3H7 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-HHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2902 CH3 + C2H4 <=> C3H7 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-HHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 9,
    label = "C=C + [CH2]CCCCC <=> [CH2]CCCCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(19.35,'cm^3/(mol*s)'), n=3.009, Ea=(6.429,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2907 C6H13-11 + C2H4 <=> C8H17-7 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2907 C6H13-11 + C2H4 <=> C8H17-7 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 10,
    label = "C=C + C[CH2] <=> [CH2]CCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(36.28,'cm^3/(mol*s)'), n=2.997, Ea=(6.866,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2903 C2H5 + C2H4 <=> C4H9-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2903 C2H5 + C2H4 <=> C4H9-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 11,
    label = "C=C + [CH2]CCCC <=> [CH2]CCCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(25.8,'cm^3/(mol*s)'), n=3.014, Ea=(6.441,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2906 C5H11-10 + C2H4 <=> C7H15-9 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2906 C5H11-10 + C2H4 <=> C7H15-9 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 12,
    label = "C=C + [CH2]CC <=> [CH2]CCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(20.13,'cm^3/(mol*s)'), n=3.003, Ea=(6.486,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 2904 C3H7-5 + C2H4 <=> C5H11-9 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2904 C3H7-5 + C2H4 <=> C5H11-9 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 13,
    label = "[H] + C=C <=> C[CH2]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.62e+08,'cm^3/(mol*s)'), n=1.64, Ea=(4.22584,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2541 H + C2H4 <=> C2H5-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2541 H + C2H4 <=> C2H5-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 14,
    label = "[CH2]CCCCC <=> C[CH]CCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(11.1,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
family: intra_H_migration
""",
)

entry(
    index = 15,
    label = "[CH2]CCCCC <=> C[CH]CCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(11.1,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
    This reaction matched rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
This reaction matched rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC]
family: intra_H_migration
""",
)

entry(
    index = 16,
    label = "[CH2]CCCCC <=> C[CH]CCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(11.1,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 17,
    label = "[CH2]CCCCC <=> C[CH]CCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(11.1,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
    This reaction matched rate rule [R5H_CCC;C_rad_out_H/NonDeC;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 112 CCCCC[CH2]-1 <=> C[CH]CCCC in intra_H_migration/training
This reaction matched rate rule [R5H_CCC;C_rad_out_H/NonDeC;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 18,
    label = "[CH2]CC <=> [H] + C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.95e+30,'s^-1'), n=-5.3, Ea=(43000,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 2920 C3H7-4 <=> propene_2 + H in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-CsH_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2920 C3H7-4 <=> propene_2 + H in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-CsH_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 19,
    label = "C[CH]CCCC <=> C=CC + [CH2]CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.77e+29,'s^-1'), n=-4.6, Ea=(38210,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 2925 C6H13-13 <=> propene_1 + C3H7-5 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-Cs\H3/H;CsJ-CsHH]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2925 C6H13-13 <=> propene_1 + C3H7-5 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-Cs\H3/H;CsJ-CsHH]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 20,
    label = "[CH2]CCCCCCCCC <=> CCCC[CH]CCCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(46.4424,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: intra_H_migration
""",
)

entry(
    index = 21,
    label = "[CH2]CCCCCCCCC <=> CCCC[CH]CCCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(25800,'s^-1'), n=1.67, Ea=(42.6768,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R6H_SSSSS;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R6H_SSSSS;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R6H_SSSSS;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R6H_SSSSS;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: intra_H_migration
""",
)

entry(
    index = 22,
    label = "[CH2]CCCCCCCCC <=> CCCC[CH]CCCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(46.4424,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: intra_H_migration
""",
)

entry(
    index = 23,
    label = "[CH2]CCCCCCCCC <=> CCCC[CH]CCCCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(262000,'s^-1'), n=1.62, Ea=(46.4424,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R5H_CCC;C_rad_out_2H;Cs_H_out_H/NonDeC] for rate rule [R5H_CCC;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: intra_H_migration
""",
)

entry(
    index = 24,
    label = "[H] + C=CCCCCC <=> [CH2]CCCCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+08,'cm^3/(mol*s)'), n=1.6, Ea=(10.0416,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 10 used for Cds-CsH_Cds-HH;HJ
    Exact match found for rate rule [Cds-CsH_Cds-HH;HJ]
    Euclidian distance = 0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
From training reaction 10 used for Cds-CsH_Cds-HH;HJ
Exact match found for rate rule [Cds-CsH_Cds-HH;HJ]
Euclidian distance = 0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 25,
    label = "[CH2]CC + C=CCCCCC <=> CCCC[CH]CCCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.15,'cm^3/(mol*s)'), n=2.992, Ea=(26.1918,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 2913 used for Cds-HH_Cds-CsH;CsJ-CsHH
    Exact match found for rate rule [Cds-HH_Cds-CsH;CsJ-CsHH]
    Euclidian distance = 0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
From training reaction 2913 used for Cds-HH_Cds-CsH;CsJ-CsHH
Exact match found for rate rule [Cds-HH_Cds-CsH;CsJ-CsHH]
Euclidian distance = 0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 26,
    label = "C=CCCCCC <=> CC=CCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 27,
    label = "CCC=CCCC <=> CC=CCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 28,
    label = "C=CC(C)CCC <=> CC=CCCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 29,
    label = "C=CC(C)CCC <=> CCC=CCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 30,
    label = "C=CC(CC)CC <=> CCC=CCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 31,
    label = "C=CC(C)CCC <=> CC=C(C)CCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 32,
    label = "CCC=C(C)CC <=> CC=C(C)CCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 33,
    label = "C=C(CC)CCC <=> CC=C(C)CCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 34,
    label = "C=C(CC)CCC <=> CCC=C(C)CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 35,
    label = "C=C(C)C(C)CC <=> CC=C(C)CCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 36,
    label = "C=C(C)C(C)CC <=> CCC=C(C)CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 37,
    label = "CC=CC(C)CC <=> CCC=C(C)CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 38,
    label = "C=CCC(C)CC <=> CC=CC(C)CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 39,
    label = "CCC=CC(C)C <=> CC=CC(C)CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 40,
    label = "CCC=CC(C)C <=> CC=CCC(C)C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 41,
    label = "C=C(C)C(C)CC <=> CCC(C)=C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 42,
    label = "C=CC(CC)CC <=> CC=C(CC)CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 43,
    label = "C=C(CC)C(C)C <=> CCC(C)=C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 44,
    label = "C=C(CC)C(C)C <=> CC=C(CC)CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 45,
    label = "CC=C(C)C(C)C <=> CCC(C)=C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 46,
    label = "C=C(CC)C(C)C <=> CC=C(C)C(C)C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 47,
    label = "C=CC(C)C(C)C <=> CCC=CC(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 48,
    label = "C=CC(C)C(C)C <=> CC=CCC(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 49,
    label = "C=CC(C)C(C)C <=> CC=C(C)C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 50,
    label = "C=CCCC(C)C <=> CC=CCC(C)C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 51,
    label = "CCC=CC(C)C <=> CCCC=C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 52,
    label = "C=C(C)CCCC <=> CCCC=C(C)C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 53,
    label = "C=CC(C)(C)CC <=> CCC=C(C)CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 54,
    label = "C=CC(C)(C)CC <=> CCCC=C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.50759e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
""",
)

entry(
    index = 55,
    label = "C=C(C)C(C)(C)C <=> CCC(C)=C(C)C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1.05228e-61,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 56,
    label = "[CH2]CC + [CH2]C=CC <=> CC=CCCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.48129e+07,'m^3/(mol*s)'), n=-0.157514, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H_Ext-1C-R_Ext-5R!H-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H_Ext-1C-R_Ext-5R!H-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H_Ext-1C-R_Ext-5R!H-R
""",
)

entry(
    index = 57,
    label = "[CH2]CC + [CH2]C=CC <=> C=CC(C)CCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.48129e+07,'m^3/(mol*s)'), n=-0.157514, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-3C-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-3C-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-3C-R
""",
)

entry(
    index = 58,
    label = "[CH2]CC + [CH2]CC=C <=> C=CCCCCC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.18795e+10,'m^3/(mol*s)'), n=-1.17734, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.298025015457, var=0.3094099417, Tref=1000.0, N=5, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R
""",
)

entry(
    index = 59,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 60,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.72e+06,'s^-1'), n=1.99, Ea=(27.2,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_H/Cd;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_H/Cd;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 61,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(7.01518e-62,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 62,
    label = "[CH2]CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.72e+06,'s^-1'), n=1.99, Ea=(27.2,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/Cd]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 84 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/Cd]
family: intra_H_migration
""",
)

entry(
    index = 63,
    label = "[CH2]CC=C <=> [CH2]C1CC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.32e+08,'s^-1'), n=0.97, Ea=(8.9,'kcal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 335 C4H7 <=> C4H7-2 in Intra_R_Add_Exocyclic/training
    This reaction matched rate rule [R4_S_D;doublebond_intra_2H_pri;radadd_intra_cs2H]
    family: Intra_R_Add_Exocyclic"""),
    longDesc = 
"""
Matched reaction 335 C4H7 <=> C4H7-2 in Intra_R_Add_Exocyclic/training
This reaction matched rate rule [R4_S_D;doublebond_intra_2H_pri;radadd_intra_cs2H]
family: Intra_R_Add_Exocyclic
""",
)

entry(
    index = 64,
    label = "[H] + C=CC=C <=> [CH2]C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.62e+08,'cm^3/(mol*s)'), n=1.64, Ea=(-1.96648,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2544 H + C4H6 <=> C4H7-9 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-CdH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2544 H + C4H6 <=> C4H7-9 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-CdH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 65,
    label = "[H] + C=CC=C <=> [CH2]CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.24e+08,'cm^3/(mol*s)'), n=1.64, Ea=(10.0416,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2580 H + C4H6-2 <=> C4H7-11 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-CdH_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2580 H + C4H6-2 <=> C4H7-11 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-CdH_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 66,
    label = "[H] + C=C=CC <=> [CH2]C=CC",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.46e+08,'cm^3/(mol*s)'), n=1.64, Ea=(15.8155,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2714 H + C4H6-4 <=> C4H7-13 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Ca_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2714 H + C4H6-4 <=> C4H7-13 in R_Addition_MultipleBond/training
This reaction matched rate rule [Ca_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 67,
    label = "C=C=CC <=> C=CC=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1.05228e-61,'s^-1'), n=22.1275, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.8800459367924431, var=31.676078103554833, Tref=1000.0, N=56, data_mean=0.0, correlation='Root_N-1R!H-inRing',), comment="""Estimated from node Root_N-1R!H-inRing
    Multiplied by reaction path degeneracy 3.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R!H-inRing
Multiplied by reaction path degeneracy 3.0
""",
)

entry(
    index = 68,
    label = "C=CC=C <=> C1=CCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.99998e+11,'s^-1'), n=0.0559095, Ea=(122.413,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH2_1;CdH2_2]
    Euclidian distance = 1.4142135623730951
    family: Intra_2+2_cycloaddition_Cd"""),
    longDesc = 
"""
Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH2_1;CdH2_2]
Euclidian distance = 1.4142135623730951
family: Intra_2+2_cycloaddition_Cd
""",
)

entry(
    index = 69,
    label = "C[CH]C <=> [CH2]CC",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(4.86e+09,'s^-1'), n=1.32, Ea=(168.615,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 146 C3H7-2 <=> C3H7 in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/NonDeC]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 146 C3H7-2 <=> C3H7 in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/NonDeC]
family: intra_H_migration
""",
)

entry(
    index = 70,
    label = "C[CH]C + [CH2]C=CC <=> CC=CCC(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.12455e+08,'m^3/(mol*s)'), n=-0.428757, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-1C-R_Ext-5R!H-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-1C-R_Ext-5R!H-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-1C-R_Ext-5R!H-R
""",
)

entry(
    index = 71,
    label = "C[CH]C + [CH2]C=CC <=> C=CC(C)C(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.48129e+07,'m^3/(mol*s)'), n=-0.157514, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-3C-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-3C-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-3C-R
""",
)

entry(
    index = 72,
    label = "C[CH]C + [CH2]CC=C <=> C=CCCC(C)C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.12455e+08,'m^3/(mol*s)'), n=-0.428757, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-1C-R_Ext-5R!H-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-1C-R_Ext-5R!H-R"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_N-3R!H->O_Ext-1C-R_Ext-5R!H-R
""",
)

entry(
    index = 73,
    label = "[H] + C=CC <=> C[CH]C",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.84e+09,'cm^3/(mol*s)'), n=1.553, Ea=(6.56888,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 2814 H + propene_1 <=> C3H7-3 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-Cs\H3/H;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2814 H + propene_1 <=> C3H7-3 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-Cs\H3/H;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 74,
    label = "C[C]C <=> C=CC",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(3.68788e+15,'s^-1'), n=-1.07844, Ea=(56.8484,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CsJ2-C;CsJ2C;CH] for rate rule [CsJ2-C;CsJ2C;CH3]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 6.0
    family: Singlet_Carbene_Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using template [CsJ2-C;CsJ2C;CH] for rate rule [CsJ2-C;CsJ2C;CH3]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 6.0
family: Singlet_Carbene_Intra_Disproportionation
""",
)

entry(
    index = 75,
    label = "[H] + [CH2]C=C[CH2] <=> [CH2]C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.25196e+07,'m^3/(mol*s)'), n=0.255122, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 76,
    label = "[H] + [CH2]C=C[CH2] <=> [CH2]CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.53274e+07,'m^3/(mol*s)'), n=0.153073, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.00248871722291, var=1.13870876508, Tref=1000.0, N=5, data_mean=0.0, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_Ext-2CN-R',), comment="""Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_Ext-2CN-R
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_Ext-2CN-R
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 77,
    label = "[CH2]C=C[CH2] <=> C=C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.4874e+09,'s^-1'), n=1.045, Ea=(63.4002,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R3radExo;Y_rad;XH_Rrad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [R3radExo;Y_rad;XH_Rrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 78,
    label = "[CH2]C=C[CH2] <=> C1=CCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.62e+12,'s^-1'), n=-0.305, Ea=(8.28432,'kJ/mol'), T0=(1,'K'), Tmin=(600,'K'), Tmax=(2000,'K'), comment="""Estimated using template [R4;C_rad_out_2H;Cpri_rad_out_2H] for rate rule [R4_SDS;C_rad_out_2H;Cpri_rad_out_2H]
    Euclidian distance = 1.0
    family: Birad_recombination"""),
    longDesc = 
"""
Estimated using template [R4;C_rad_out_2H;Cpri_rad_out_2H] for rate rule [R4_SDS;C_rad_out_2H;Cpri_rad_out_2H]
Euclidian distance = 1.0
family: Birad_recombination
""",
)

entry(
    index = 79,
    label = "[CH2]C=C[CH2] => C=CC=C",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(5.01e+07,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 5 C4H6 => C4H6-2 in 1,2-Birad_to_alkene/training
    This reaction matched rate rule [Y_12_01]
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Matched reaction 5 C4H6 => C4H6-2 in 1,2-Birad_to_alkene/training
This reaction matched rate rule [Y_12_01]
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 80,
    label = "[H] + [CH2]C=C <=> C=CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.84e+13,'cm^3/(mol*s)'), n=0.18, Ea=(0.518816,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(2000,'K'), comment="""Matched reaction 121 H + C3H5 <=> C3H6-2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 121 H + C3H5 <=> C3H6-2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN_Ext-3C-R_Sp-4R!H=3C_N-3C-inRing]
family: R_Recombination
""",
)

entry(
    index = 81,
    label = "C[CH2] + [CH2]C=C <=> C=C + C=CC",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(1.374e+14,'cm^3/(mol*s)','*|/',3), n=-0.35, Ea=(-0.54392,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 7 C3H5 + C2H5 <=> C3H6 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 7 C3H5 + C2H5 <=> C3H6 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R]
family: Disproportionation
""",
)

entry(
    index = 82,
    label = "[CH2]C=C + [CH2]CCC <=> C=CCCCCC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(6.96258e+07,'m^3/(mol*s)'), n=-0.157514, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H_Ext-1C-R_Ext-5R!H-R',), comment="""Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H_Ext-1C-R_Ext-5R!H-R
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-3R!H-R_N-Sp-3R!H=2R_Sp-4R!H=3R!H_Ext-1C-R_Ext-5R!H-R
Multiplied by reaction path degeneracy 2.0
""",
)

