#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "C[CH2] + [CH2]CCCC <=> n-heptane",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[12.8544,0.353621,-0.0627269,-0.00386692],[-1.10003,0.653392,-0.10983,-0.00929697],[-0.598326,0.511962,-0.0705911,-0.0123676],[-0.367072,0.332335,-0.0255785,-0.0136063],[-0.203354,0.167989,0.00822183,-0.0110344],[-0.0917774,0.0537379,0.0233019,-0.00578355]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 1,
    label = "[CH2]CC + [CH2]CCC <=> n-heptane",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[12.8363,0.370008,-0.0629218,-0.00430749],[-1.13335,0.682505,-0.109337,-0.0102196],[-0.624054,0.531861,-0.0680981,-0.0132958],[-0.383516,0.341595,-0.0213782,-0.014292],[-0.211774,0.169076,0.012785,-0.0111922],[-0.094981,0.0508026,0.0268825,-0.00536413]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 2,
    label = "[CH2]CC + [CH2]CCC <=> C[CH2] + [CH2]CCCC",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[7.82011,-1.91528,-0.0883434,-0.00816893],[4.35831,1.00929,-0.129481,-0.0210864],[0.407162,0.629421,-0.0280507,-0.0266886],[-0.292258,0.241427,0.0503068,-0.0203131],[-0.226933,-0.000314109,0.0654369,-0.00332428],[-0.0769324,-0.0779425,0.036021,0.0113585]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 3,
    label = "C=C + [CH2]CC <=> [CH2]CCCC",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[6.77343,0.54421,-0.110835,0.000671979],[2.67453,0.917576,-0.151899,-0.0151286],[-0.199938,0.558743,-0.0246076,-0.0336654],[-0.190484,0.246834,0.0542585,-0.0278511],[-0.115062,0.0810563,0.0631799,-0.00782826],[-0.0682522,0.0231725,0.0415816,0.00534871]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 4,
    label = "C=C + C[CH2] <=> [CH2]CCC",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[6.74993,0.626952,-0.102219,-0.00392008],[2.61617,1.04018,-0.132885,-0.0192717],[-0.286414,0.581386,-0.000525368,-0.0296183],[-0.190115,0.1895,0.0732027,-0.0169575],[-0.0755811,0.00525829,0.0663966,0.00448532],[-0.0327413,-0.0250213,0.0298163,0.0136128]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 5,
    label = "[CH3] + C=C <=> [CH2]CC",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[7.67161,0.820335,-0.118557,0.00617502],[2.38567,1.16374,-0.0726919,-0.0267186],[-0.367014,0.46154,0.0693105,-0.0231855],[-0.15338,0.0665817,0.0661074,0.00559326],[-0.0192407,-0.0445467,0.0201041,0.0131727],[0.0176656,-0.03637,-0.00402369,0.00551617]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 6,
    label = "[H] + C=C <=> C[CH2]",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[11.9749,0.935193,-0.179389,0.0171452],[-0.175312,0.980596,-0.0113884,-0.0396637],[-0.449748,0.345349,0.0717718,-0.011642],[-0.206497,0.0745392,0.0391567,0.00704515],[-0.0587199,-0.00975733,0.00845425,0.00599679],[0.00404497,-0.0205232,-0.0032982,0.00131119]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 7,
    label = "[H] + C[CH2] <=> [H][H] + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1.083e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_2R!H->C]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_2R!H->C]
family: Disproportionation
""",
)

entry(
    index = 8,
    label = "[H] + [H] <=> [H][H]",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[8.44632,1.75047,-0.229908,-0.0184533],[0.0402101,0.255859,0.0763614,-0.0212147],[-0.109283,0.0493817,0.0017666,-0.00204123],[-0.0409012,0.0126129,0.00192065,0.00217847],[-0.0161023,0.00398719,0.00159691,0.00140017],[-0.00620692,0.00146359,0.000703885,0.000606165]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 9,
    label = "[CH3] + [CH3] <=> [H] + C[CH2]",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[7.77169,-1.03457,-0.306505,0.0131066],[4.4369,0.911944,0.169225,-0.0736144],[0.234008,0.193301,0.131808,0.0246126],[0.0581886,-0.0116864,0.0306523,0.030286],[0.00379499,-0.0414154,-0.0112482,0.0100945],[-0.00265266,-0.0259443,-0.0155355,-0.00261292]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 10,
    label = "[CH]=C + C[CH2] <=> C=C + C=C",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(4.56e+14,'cm^3/(mol*s)','*|/',1.5), n=-0.7, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 11 C2H3-2 + C2H5 <=> C2H4-2 + C2H4 in Disproportionation/training
    This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 11 C2H3-2 + C2H5 <=> C2H4-2 + C2H4 in Disproportionation/training
This reaction matched rate rule [Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS]
family: Disproportionation
""",
)

entry(
    index = 11,
    label = "[H] + [CH]=C <=> C=C",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[12.9313,1.35321,-0.380737,0.0111606],[-0.799053,0.4774,0.113682,-0.0390218],[-0.502481,0.232372,0.0726219,-0.0071662],[-0.277566,0.0853714,0.0353412,0.00434905],[-0.14336,0.0243049,0.0130557,0.00411962],[-0.0703809,0.00439538,0.00337158,0.001757]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 12,
    label = "[H] + C=C <=> [H][H] + [CH]=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(240,'cm^3/(mol*s)'), n=3.62, Ea=(11266,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 217 C2H4 + H <=> C2H3_p + H2_p in H_Abstraction/training
    This reaction matched rate rule [Cd/H2/NonDeC;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 217 C2H4 + H <=> C2H3_p + H2_p in H_Abstraction/training
This reaction matched rate rule [Cd/H2/NonDeC;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 13,
    label = "[H] + [CH]=C <=> [H][H] + C#C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(480,'m^3/(mol*s)'), n=1.5, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.13686319048999, Tref=1000.0, N=1, data_mean=0.0, correlation='Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C',), comment="""Estimated from node Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 14,
    label = "[CH]=C + [CH]=C <=> C#C + C=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.9597e+07,'m^3/(mol*s)'), n=-0.311932, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.14761419944759951, var=0.2702865095049491, Tref=1000.0, N=6, data_mean=0.0, correlation='Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O',), comment="""Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
    Multiplied by reaction path degeneracy 2.0"""),
    longDesc = 
"""
Estimated from node Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
Multiplied by reaction path degeneracy 2.0
""",
)

entry(
    index = 15,
    label = "[H] + C#C <=> [CH]=C",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[11.4307,1.24869,-0.202776,0.00671998],[-0.112597,0.911927,0.0738463,-0.0324581],[-0.483168,0.193898,0.0694086,0.0076989],[-0.197027,0.0172733,0.0150976,0.00699785],[-0.0609736,-0.00942288,-0.00105634,0.000879496],[-0.00771835,-0.00784392,-0.00220493,-0.000522074]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

entry(
    index = 16,
    label = "[CH3] + [CH]=C <=> C[C]C",
    degeneracy = 1.0,
    kinetics = Chebyshev(coeffs=[[13.1016,-0.800677,-0.30497,-0.0164927],[0.641706,0.74444,0.231896,-0.0284039],[0.110003,0.151412,0.101539,0.0331485],[-0.0273775,-0.0322635,0.00674673,0.0205333],[-0.0330608,-0.0467291,-0.0202669,0.00056749],[-0.0146259,-0.0225256,-0.0154513,-0.00645765]], kunits='cm^3/(mol*s)', Tmin=(300,'K'), Tmax=(3000,'K'), Pmin=(0.001,'bar'), Pmax=(100,'bar')),
)

